name: Generate ASCII Artwork

on:
    push

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get isntall cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a Dragon...RAWR" >> dragon.txt
        
        - name: Sleep for 30 seconds
          run: sleep 30
        
        # uses: actions/checkout@v4
        
        # - name: List Repo Files
        #   run: ls -ltra

        # - name: Executing Shell Script
        #   run: | 
        #      chmod +x ascii-script.sh
        #      ./ascii-script.sh

    test_job_2:
        runs-on: ubuntu-latest
        steps:
        - name: Sleep for 10 seconds
          run: sleep 10

        - name: File Exists
          run: grep -i "dragon" dragon.txt 
    
    deploy_job_3:
        runs-on: ubuntu-latest
        steps: 
        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying ... .. .